AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ParameterName:
    Type: String
    Default: Test
  Value1Parameter:
    Type: String
    Default: value1
  Value2Parameter:
    Type: String
    Default: value2
Resources:
  SSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Ref ParameterName
      Type: String
      Value: !Sub
        - |
          {
             "key1": "${value1}"
             "key2": "${value2}"
          }
        - value1: !Ref Value1Parameter
          value2: !Ref Value2Parameter
