name: run_script_no_args
on:
  workflow_dispatch:
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: pwd && ls
